apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclass
spec:
  replicas: 2
  selector:
    matchlabels:
      app: imageclassifier
  template:
    metadata:
      labels:
        app: imageclassifier
    spec:
      containers:
      -name: cv-app
      image: gcr.io/pjanjanam/imgwebapp:v1
      ports:
      - containerPort: 8501
